name: session_mate_core
description: The package that stores the models used for session_mate package and cli
version: 0.2.2
repository: https://github.com/FilledStacks/session_mate_core

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  xml: ^6.3.0
  xml2json: ^5.3.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  lints: ^2.0.0
  test: ^1.21.0
